baseURL = 'https://isaiahnullbyte.github.io/cybernautblog/'
languageCode = 'en-us'
title = 'The Cybernaut Blog'
theme = 'terminal'
[params]
 fullWidthTheme = true

[languages]
  [languages.en]
    [languages.en.params.logo]
      logoText = "./Cybernaut_Journal"
      logoHomeLink = "/"
